VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
HORIZON_URL="https://horizon.publicnode.org"

ACCOUNTS=[
   "GDUFFVLW4IJVVI2OMTFGCH3ECVHKKV5U6DJ2XWUBDSYGDABNOLJQG64C"
]

[DOCUMENTATION]
ORG_NAME="Jaws Crypto LLC"
ORG_URL="https://www.jaws.com"
ORG_OFFICIAL_EMAIL="crypto@jaws.com"

[[VALIDATORS]]
ALIAS="oxford"
DISPLAY_NAME="Oxford"
HOST="stellar01.jaws.com:11625"
PUBLIC_KEY="GDUFFVLW4IJVVI2OMTFGCH3ECVHKKV5U6DJ2XWUBDSYGDABNOLJQG64C"
